
// joining strings together
var greeting = "Hi";
var myName = " Marema";
greeting + myName; 

// finding the length of a string
"Marema".length;

"strawberry".length;

// getting a single character
// use square brackets for indexing
// indexing always starts at zero
var myName = "Marema";
myName[2];


// getting a single character
// use square brackets for indexing
// indexing always starts at zero
var myName = "Marema";
myName[6];

// getting a single character
// use square brackets for indexing
// indexing always starts at zero
var myName = "Marema";
myName[0];


// post incrementation increases the value after using it
// post incrementation always starts with the current value
var numbers = 19;
numbers++; 


// after starting with the current value it will then display the new one when using the ++ again
numbers++; 



// pre incrementation increases the value before using it, meaning it starts with the new value already and not the current one
var numbers = 35;
++numbers;


