//Not operator (!) Changes the condition that is false into true and the condition that is true into false.

//creating a variable name (isWeekend) and assigning it the value (true)
var isWeekend = true;

//creating a variable name (needToShowerToday) and assigning it the variable  (isWeekend) and using the not (!) operator to make it false
var needToShowerToday = !isWeekend;

//calling the needToShowerToday varaible which will display the value false.
needToShowerToday;