
//Primitive
// creating a variable name (color) and assigning it a value string (blue).
var color = "blue";

//Calling the variable color which will display the value blue.
color;

//changing the color from blue to yellow by just using the variable and the new value only
color = "yellow";

//Calling the variable color which will display the value yellow.
color;

//creating a new varaible (i) and assign it the varaible (color) which means that i will then have access to the value of the variable color.
var i = color;

//Calling the variable i which will display the value yellow.
i;